e_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    AboutView,
)

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make-order'),
    path('about/', AboutView.as_view(), name='about'),
]

mainapp/models.py
from PIL import Image

from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from django.urls import reverse
from django.utils import timezone

User = get_user_model()


# Метод для добавления сразу всех моделей и отражения на сайте товаров из категорий
def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass


class MaxSizeErrorException(Exception):
    pass


class LatestProductsManager:

    # Отображение товаров на главной странице, путем собирания товаров из нужных моделей
    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')  # 1.0 Приоритетность отображения товаров на странице
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)

        # 1.1 Приоритетность отображения товаров на странице
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to),
                                  reverse=True)
        return products


class LatestProducts:

    objects = LatestProductsManager()


# Менеджер категорий - создаем класс для отражение списка товаров в списке Shop
class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count',
        'Смартфоны': 'smartphone__count',
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):

    MIN_RESOLUTION = (400, 400)
    MAX_RESOLUTION = (3000, 2800)
    MAX_IMAGE_SIZE = 3145728

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.title

    # Метод для удаления товара из корзины
    def get_model_name(self):
        return self.__class__.__name__.lower()

    # Переопределяем метод Save для корректного сохранения изображения
    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)
        min_height, min_width = self.MIN_RESOLUTION
        max_height, max_width = self.MAX_RESOLUTION
        if image.size > self.MAX_IMAGE_SIZE:
            raise MaxSizeErrorException('Размер изображения не должен превышать 3 МВ!')
        if img.width < min_width or img.height < min_height:
            raise MinResolutionErrorException('Разрешение изображения меньше минимального!')
        if img.width > max_width or img.height > max_height:
            raise MaxResolutionErrorException('Разрешение изображения больше максимального!')
        super().save(*args, **kwargs)


class Notebook(Product):

    diagonal = models.CharField(max_length=255, verbose_name='Диагональ')
    display_type = models.CharField(max_length=255, verbose_name='Тип дисплея')
    processor_freq = models.CharField(max_length=255, verbose_name='Частота процессора')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    video = models.CharField(max_length=255, verbose_name='Видеокарта')
    time_without_charge = models.CharField(max_length=255, verbose_name='Время работы аккумулятора')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Smartphone(Product):

    diagonal = models.CharField(max_length=255, verbose_name='Диагональ')
    display_type = models.CharField(max_length=255, verbose_name='Тип дисплея')
    resolution = models.CharField(max_length=255, verbose_name='Разрешение экрана')
    accum_volume = models.CharField(max_length=255, verbose_name='Объем батареи')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    sd = models.BooleanField(default=True, verbose_name='Наличие SD карты')
    sd_volume_max = models.CharField(max_length=255, null=True, blank=True, verbose_name='Максимальный объем'
                                                                                         ' встраемовой памяти')
    main_cam_mp = models.CharField(max_length=255, verbose_name='Главная камера')
    front_cam_mp = models.CharField(max_length=255, verbose_name='Фронтальная камера')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')

    # @property
    # def sd(self):
    #     if self.sd:
    #         return 'Да'
    #     return 'Нет'


class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.content_object.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):

    owner = models.ForeignKey('Customer', null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_customer')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):

    # Статусы заказов
    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    # Тип доставки
    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен'),
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка'),
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)

    # Статус заказа
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказа',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )

    # Варианты доставки
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(verbose_name='Дата получения заказа', default=timezone.now)

    def __str__(self):

mainapp/forms.py
from django import forms

from .models import Order


# Форма заказа покупателя. P.S Устанавливаем django-crispy-forms для хорошего отображения формы
class OrderForm(forms.ModelForm):

    # Переопределяем название после редактирования формы
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = "Дата получения заказа"

    # Редактируем поле формы дата (делаем календарь)
    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment',
        )

mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}


# JavaScript для кастомизации полей SD карты
{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
   $('#id_sd').on('click', function (){
       if($('#id_sd_volume_max').prop('checked') == true){
           $('#id_sd_volume_max').prop('readonly', false)
           $('#id_sd_volume_max').val('')
           $('#id_sd_volume_max').css('background', 'white')
       }else{
           $('#id_sd_volume_max').prop('readonly', true)
           $('#id_sd_volume_max').val('')
           $('#id_sd_volume_max').css('background', 'lightgrey')
       }
   })
})(django.jQuery);

</script>
{% endblock %}

mainapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=Blg1G-ePMrSthUsyTtTTK1_ZoV_LmS_B9X1naG40TTcn3cyV6gXd8kasIPs71TcvK9_HAnSNgbIl1qwS-RrbxWmTb78aXBbq7iGVHKs1aWY" charset="UTF-8"></script></head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" style="background: #A8A8A8;">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">Pet project E-market</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Главная</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">О нас</a></li>
                    </ul>
                        <div class="dropdown">
                            <button class="btn btn-outline-dark dropdown-toggle" data-toggle="dropdown">Каталог</button>
                            <ul class="dropdown-menu">
                                {% for category in categories %}
                                    <li><a href="{{ category.url }}"> {{ category.name }} ({{ category.count }})</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    <a class="navbar-brand" href="{% url 'cart' %}">
                        <button class="btn btn-outline-dark">
                            <span class="bi-cart-fill me-1">Корзина</span>

                            <span class="badge bg-dark text-white ms-1 rounded-pill">{{ cart.products.count }}</span>
                        </button>
                    </a>
                </div>
            </div>
        </nav>
        <!-- Section-->
        {% block content %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success alert-dismissible fade show text-center" style="margin-left: 20%; margin-right: 20%;" role="alert">
                    <strong>{{ message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        <section class="py-5">
            {% for product in products %}
            <div class='product_info' style="display: inline-block; text-align: center; padding: 10px 0; margin: 0 10px 20px 20px; max-width: 80%; margin-left: 12%;">
                <img class="card-img-top" style="width: 200px;" src="{{ product.image.url }}" alt="..." />
                <h5>{{ product.title }}</h5>
                {{product.price }} руб.
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ product.get_absolute_url }}">Подробнее</a></div>
                    <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                        <button class="btn btn-danger" style="margin-top: 10px; margin-left: 5px; margin-right: 5px;">Добавить в корзину</button>
                    </a>
                </div>
            </div>
            {% endfor %}
        </section>
        {% endblock content %}

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
      <!-- Core theme JS-->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

mainapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %}пуста{% endif %}</h3>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show text-center" style="margin-left: 20%; margin-right: 20%;" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    {% if cart.products.count %}
    <table class="table text-center" style="max-width: 80%; margin-left: 10%;">
      <thead>
        <tr>
            <th scope="col">Наименование товара</th>
            <th scope="col">Изображение</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th scope="col">Общая цена</th>
            <th scope="col">Действие</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cart.products.all %}
            <tr>
                <th scope="row">{{ item.content_object.title }}</th>
                <td class="w-25"><img src="{{ item.content_object.image.url }}" width="300" height="200" class="img-fluid"></td>
                <td>{{ item.content_object.price }} руб.</td>
                <td>
                    <form action="{% url 'change_qty' ct_model=item.content_object.get_model_name slug=item.content_object.slug  %}" method="POST">
                        {% csrf_token %}
                        <input type="number" class="form-control" name="qty" style="width: 70px;" min="1" value="{{ item.qty }}">
                        <br>
                        <input type="submit" class="btn btn-primary" value="Изменить количество">
                    </form>
                </td>
                <td>{{ item.final_price }} руб.</td>
                <td>
                    <a href="{%  url 'delete_from_cart' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}"><button class="btn btn-danger">Удалить из корзины</button></a>
                </td>
            </tr>
        {% endfor %}
            <tr>
                <td colspan="2"></td>
                <td>Итого:</td>
                <td>{{ cart.total_products }}</td>
                <td><strong>{{ cart.final_price }} руб.</strong></td>
                <td><a href="{% url 'checkout' %}"><button class="btn btn-primary">Перейти к оформлению</button></a></td>
            </tr>
      </tbody>
    </table>
    {% endif %}
{% endblock content %}

mainapp/templates/category_detail.html
{% extends 'base.html' %}

{% block content %}
    <nav aria-label="breadcrumb" class="mb-4">
      <ol class="breadcrumb" style="margin-left: 20px">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item active">{{ category.name }}</li>
      </ol>
    </nav>

<section class="py-5">
    {% for product in category_products %}
    <div class='product_info' style="display: inline-block; text-align: center; padding: 10px 0; margin: 0 10px 20px 20px; max-width: 80%; margin-left: 12%;">
        <img class="card-img-top" style="width: 200px;" src="{{ product.image.url }}" alt="..." />
        <h5>{{ product.title }}</h5>
        {{product.price }} руб.
        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ product.get_absolute_url }}">Подробнее</a></div>
            <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                <button class="btn btn-danger" style="margin-top: 10px; margin-left: 5px; margin-right: 5px;">Добавить в корзину</button>
            </a>
        </div>
    </div>
    {% endfor %}
</section>

{% endblock content %}

mainapp/templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h3 class="text-center mt-5 mb-5">Оформление заказа</h3>
<table class="table text-center" style="max-width: 80%; margin-left: 10%;">
    <thead>
        <tr>
            <th scope="col">Наименование товара</th>
            <th scope="col">Изображение</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th scope="col">Общая цена</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart.products.all %}
            <tr>
                <th scope="row">{{ item.content_object.title }}</th>
                <td class="w-25"><img src="{{ item.content_object.image.url }}" width="300" height="200" class="img-fluid"></td>
                <td>{{ item.content_object.price }} руб.</td>
                <td>{{ item.qty }}</td>
                <td>{{ item.final_price }} руб.</td>
            </tr>
        {% endfor %}
            <tr>
                <td colspan="2"></td>
                <td>Итого:</td>
                <td>{{ cart.total_products }}</td>
                <td><strong>{{ cart.final_price }} руб.</strong></td>
            </tr>
    </tbody>
</table>
<hr>
<h3 class="text-center mt-5 mb-5" style="max-width: 80%; margin-left: 10%;"> Форма заказа</h3>
<form action="{% url 'make-order' %}" method="POST">
    <div class="text-left" style="max-width: 80%; margin-left: 10%; margin-bottom: 30px;">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-success btn-block mb-3" value="Оформить заказ">
    </div>
</form>
{% endblock content %}

mainapp/templates/notebook_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display_type }}</td>
    </tr>
    <tr>
      <td>Частота процессора</td>
      <td>{{ product.processor_freq }}</td>
    </tr>
    <tr>
      <td>Оперативная память</td>
      <td>{{ product.ram }}</td>
    </tr>
    <tr>
      <td>Видеокарта</td>
      <td>{{ product.video }}</td>
    </tr>
    <tr>
      <td>Время работы аккумулятора</td>
      <td>{{ product.time_without_charge }}</td>
    </tr>
  </tbody>
</table>

mainapp/templates/product.detail.html
{% extends 'base.html' %}
{% load specifications %}

{% block content %}

    <nav aria-label="breadcrumb" class="mb-4">
      <ol class="breadcrumb" style="margin-left: 20px">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item"><a href="#">{{ product.category.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
      </ol>
    </nav>

<div class="row" style="margin-left: 20px">
    <div class="col-md-4">
        <img src="{{ product.image.url }}" width="300" height="200" class="image-fluid">
    </div>
    <div class="col-md-7" style="text-align: justify">
        <h3>{{ product.title }}</h3>
        <p>Цена: {{ product.price }} руб.</p>
        <p>Описание: {{ product.description }}</p>
        <hr>
        <a href="{% url 'add_to_cart' ct_model=ct_model slug=product.slug %}"><button class="btn btn-danger">Добавить в корзину</button></a>
    </div>
    <p class="mt-4"> Характеристики: </p>

    {{ product|product_spec }}

</div>

{% endblock content %}

mainapp/templates/smartphone_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display_type }}</td>
    </tr>
    <tr>
      <td>Разрешение экрана</td>
      <td>{{ product.resolution }}</td>
    </tr>
    <tr>
      <td>Объем батереи</td>
      <td>{{ product.accum_volume }}</td>
    </tr>
    <tr>
      <td>Оперативная память</td>
      <td>{{ product.ram }}</td>
    </tr>
    <tr>
      <td>Наличие слота для SD карты</td>
      <td>{{ product.sd }}</td>
    </tr>
    <tr>
      <td>Максимальный объем SD карты</td>
      <td>{{ product.sd_volume_max }}</td>
    </tr>
    <tr>
      <td>Камера (МП)</td>
      <td>{{ product.main_cam_mp }}</td>
    </tr>
    <tr>
      <td>Фронтальная камера (МП)</td>
      <td>{{ product.front_cam_mp }}</td>
    </tr>
  </tbody>
</table>